name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build debug
      run: cargo build
    - name: Build release
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: linux-binary-debug
        path: target/debug/ppoker
    - uses: actions/upload-artifact@v4
      with:
        name: linux-binary-release
        path: target/release/ppoker
